name: Generate Sitemap

on:
  push:
    branches: [main]
    paths:
      - 'cocktails/**.json'
      - '.github/workflows/update-sitemap.yml'
      - 'generate-sitemap.js'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate sitemap.xml
        run: node generate-sitemap.js

      - name: Commit and push sitemap
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUSH_TOKEN }}
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git checkout main
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml" || echo "No changes to commit"
          git pull origin main --rebase
          git push origin HEAD:main
