name: Generate Sitemap

on:
  push:
    branches: [main]
    paths:
      - 'cocktails/**.json'
      - '.github/workflows/update-sitemap.yml'
      - 'generate-sitemap.js'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Generate sitemap.xml
        run: node generate-sitemap.js

      - name: Commit and push sitemap
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add sitemap.xml
          git commit -m "Auto-update sitemap.xml"
          git push
        continue-on-error: true
